### ISSUE TITLE
How do I use the tiles

### ISSUE THREAD

**Issue by luandro** [karissa/tile-download-ui#8]
Sorry for the noob question. But once I've downloaded a set of images, how do I call them in HTML or JS to render a map?

**Comment by hackergrrl** [comment]
@luandro What are you using to render the map? For mapbox-gl-js, I wonder if a configuration like [this](https://gist.github.com/danswick/a4de5c170c04fdd38bb4) would work? You'd need a local http server to serve them up. You could extract the tar archive, or use [indexed-tarball](https://github.com/digidem/indexed-tarball) to serve them right from the archive.
